pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"
        ECR_REPO = "924263791418.dkr.ecr.ap-south-1.amazonaws.com/epc-frontend"
        IMAGE_TAG = "${BUILD_NUMBER}"
        FRONTEND_SERVER = "65.1.85.177"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('epc-frontend-main') {
                    sh 'npm install'
                }
            }
        }

        stage('Build Application') {
            steps {
                dir('epc-frontend-main') {
                    sh 'npm run build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('epc-frontend-main') {
                    sh '''
                    docker build --no-cache -t epc-frontend:${IMAGE_TAG} .
                    '''
                }
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login --username AWS --password-stdin 924263791418.dkr.ecr.ap-south-1.amazonaws.com
                '''
            }
        }

        stage('Tag Image') {
            steps {
                sh '''
                docker tag epc-frontend:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}
                '''
            }
        }

        stage('Push Image to ECR') {
            steps {
                sh '''
                docker push ${ECR_REPO}:${IMAGE_TAG}
                '''
            }
        }

        stage('Deploy to Frontend Production') {
            steps {
                sshagent(credentials: ['frontend-key']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ubuntu@${FRONTEND_SERVER} '
                    aws ecr get-login-password --region ${AWS_REGION} | sudo docker login --username AWS --password-stdin 924263791418.dkr.ecr.ap-south-1.amazonaws.com

                    sudo docker pull ${ECR_REPO}:${IMAGE_TAG}

                    sudo docker stop epc-frontend || true
                    sudo docker rm epc-frontend || true

                    sudo docker run -d \
                      --name epc-frontend \
                      -p 80:80 \
                      --restart always \
                      ${ECR_REPO}:${IMAGE_TAG}
                    '
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'Production deployment completed successfully.'
        }

        failure {
            echo 'Production deployment failed.'
        }

        always {
            cleanWs()
        }
    }
}
