pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('epc-frontend-main') {
                    sh 'npm install'
                }
            }
        }

        stage('Build Application') {
            steps {
                dir('epc-frontend-main') {
                    sh 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                dir('epc-frontend-main') {
                    sh 'npm test -- --watch=false || true'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully'
        }
        failure {
            echo 'Pipeline execution failed'
        }
    }
}
